### ISSUE TITLE
validation not working

### ISSUE THREAD

**Issue by jason-szot** [jason-szot/word-clone#1]
input validation is not working, shows every entry is wrong:
    |---+---+---|       Menu:
    | E | R | I |       1. Shuffle letters.
    |---+---+---|       2. Guess a word.
    | Q | V | G |       3. Quit.
    |---+---+---|       -------------------
    | I | N | U |
    |---+---+---|       Current Score: 0
Make a choice from the menu:  2

Enter a word that is between 4 and 9 characters, and contains the center letter of the box: vine
VINE
_That word is either incorrect, does not contain the center letter, or has been entered before. Try again!_

**Comment by coopereric** [comment]
Mine seems to be working fine. The only think I can think of right now is maybe the word being entered "vine' is not a word within that file that's currently loaded.. 

![image](https://cloud.githubusercontent.com/assets/8058873/11566063/643d3516-99a6-11e5-90f4-bdf0dd331723.png)

**Comment by log-m** [comment]
Think I fixed it. One of the counters in compareFoundWords wasn't resetting, which made it mess up if you entered two words that were the same size and only differed on the last letter. I'll push the new userWordInput.asm now

**Comment by jason-szot** [comment]
yes, log-m fixed this, thanks
